### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#265]
I noticed in our last refactor we stripped out most of our logs. We need to reinstate them.
We're decided on using Logrus, but it supports multiple formats. I feel like it'd be a much more useful if our Request/Response logs were in JSON.

Opinions?

**Comment by mrd0ll4r** [comment]
Yeah, we could need more logging. If we do go with JSON for request/response logs (for debugging, right?), can we make it so they go to a different `io.Writer`? It'd be a pain to separate JSON from non-JSON log lines later.

**Comment by mrd0ll4r** [comment]
Our latest changes to logging has some negative impact on performance. I've seen that in prometheus metrics collect before and after we added a bunch of debug logs like [this](https://github.com/chihaya/chihaya/blob/master/middleware/middleware.go#L64).
The problem is that the `log.WithFields` allocates an `*logrus.Entry` just to not do anything with it as soon as `Debug` is called and no debug logging is enabled.

We could use `GetLevel` to figure out if we have debug logging on before executing that line, but that uses a mutex on the logger, see [the source](https://github.com/sirupsen/logrus/blob/master/exported.go#L38). Maybe we should just put an immutable boolean somewhere to indicate whether we have debug logging?

**Comment by jzelinskie** [comment]
Tangentially, I've been thinking to help reduce some of the verbosity of creating a `pkg/log` package that implements functions like

```go
func Log(level logrus.Level, message string, fields ...LogFielder)

type LogFielder interface {
  LogFields() logrus.LogFields
}
```

**Comment by mrd0ll4r** [comment]
Sounds good, we can make that check for the log level too.

**Comment by mrd0ll4r** [comment]
For tracking: 

- JSON logging has been done in #313 
- Implementing a wrapper package has been done in #340

I feel like this issue is fixed. We have a bunch of debug logs now and a good framework for adding more.
