### ISSUE TITLE
Improve logging of hooks in use

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#317]
We now log what hooks are in use. However, we just print their addresses in memory, which in turn doesn't help a lot.

**Comment by cedricgc** [comment]
I am assuming that we want the hook names logged instead of memory addresses. Here is something I created quickly to confirm.

<img width="552" alt="screen shot 2017-05-21 at 4 17 06 pm" src="https://cloud.githubusercontent.com/assets/4852029/26287438/1dabb5be-3e41-11e7-8763-835dda3da36a.png">

The main thing is that we want the name field from hookConfig struct but CreateHooks returns []middleware.Hook, which is just an interface.

**Comment by jzelinskie** [comment]
This looks good except for the inability to distinguish middleware with spaces in their names: `client approval` is one middleware, but appears like two in the above screenshot.

**Comment by cedricgc** [comment]
Agreed, the log is clear with the JSON formatter but the key-value logrus formatter seems to string slices in that form without commas. Not sure if I can override logrus behavior here. I can wrap the names in quotes but it would make the JSON representation look weird.

**Comment by cedricgc** [comment]
Hello, If I can get input on how to handle what @jzelinskie mentioned I can finish this up. The issue is the formatting with Logrus' TextFormatter. From looking at the Logrus documentation I did not see a way to override formatting globally or once at the log call. I can wrap the Strings as mentioned before but it would effect the JSON output.

Should I open a PR now for feedback?

**Comment by jzelinskie** [comment]
Yup. I think this is slightly non-ideal, but still totally acceptable! Please do.
