### ISSUE TITLE
Middleware Insert Random IP Addresses

### ISSUE THREAD

**Issue by plumpudding** [chihaya/chihaya#324]
Add a middleware that inserts one completely random IP address from a range known to be used for plausible deniability

https://web.archive.org/web/20161119070913/http://opentracker.blog.h3q.com/2007/02/12/perfect-deniability/

**Comment by hydra-zone** [comment]
That sounds like a good idea for public trackers, I think OpenTracker already supports this via a plug-in

Wikipedia says "Because there have already been cases of people being accused of copyright violation by the fact that their IP address was listed on a BitTorrent tracker,[2] opentracker may mix in random IP address numbers for the purpose of plausible deniability."

**Comment by mrd0ll4r** [comment]
Hah, I alread wrote that :)

To be found here: https://github.com/mrd0ll4r/chihaya/tree/deniability/middleware/deniability
Although that might not work out of the box with the current chihaya. Also it doesn't perform super good yet, and getting it right proved to be more difficult that anticipated.
Documentation about the configuration can be found [here](https://github.com/mrd0ll4r/chihaya/blob/deniability/docs/middleware/deniability.md). No guarantee about that being up-to-date.

The (not merged) PR with all the comments on why this is more difficult than it seems is #252 .

**Comment by mrd0ll4r** [comment]
Upon reading through that PR again, we have two possible options:

1. Write a PostHook that randomly inserts peers into the **storage**. They will be kept in the storage, garbage-collected after some time, and randomly selected like other peers for subsequent announces.
    The advantage to this is that they are indistinguishable from real peers even from Chihaya's perspective. Scrapes would be consistent too.
    The disadvantage to this is that the fake Peers take up actual space.
2. Write a PreHook like the one I already wrote that generates Peers on the fly and inserts them into an announce response. The problems are as described in the PR, mainly:
    - Scrapes are inconsistent
    - Subsequent announces are inconsistent
    - Unless we make the _response_ hook (which is the one mandatory PreHook you really need to run a tracker, it interacts with the storage) a "user-level", orderable, configurable middleware, we will be limited in what we can do with this hook. We for example can't insert peers at random positions, the best thing we could have is a bunch of random peers at the beginning of an announce response's peer list.

Or, crazy idea: Implement this in the storage. Either as an option in the memory storage, which is gonna affect performance negatively, or make a new peer store that wraps the memory store and then inserts random peers and stuff. Wouldn't make scrapes and subsequent announces consistent, but doesn't take up additional space for the peers and doesn't need the _response_ hook to be orderable.

**Comment by jzelinskie** [comment]
After implementing this feature in the past and discussing it at length, I think we agree that this is not a feature we'll add out-of-the-box. It adds significant complexity to whatever subsystem we would add it to for only speculative value.

Trolls that sit on trackers attempt to connect to peers and if they do, then they send troll emails to the ISP. Providing them fake peers will do nothing, since they will fail to connect to the fake peers. There's also no way to prove a tracker is operating with this feature.
