### ISSUE TITLE
http and https  Simultaneous ？

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#410]
Some old clients only support http,
So you need http and https,
How to configure?

**Comment by mdkozlowski** [comment]
honestly I think your best bet would be to use something like Nginx in front of chihaya to serve both HTTP and HTTPS traffic. this would also solve your problem of requiring TLS 1.3 support without any additional work from chihaya's side

**Comment by f4nff** [comment]
If you apply nginx again, it will bring extra overhead.
And in a high concurrency environment, there will be many problems, such as the local port limit of up to 65535.

**Comment by elico** [comment]
@f4nff +1 on this.
There are solutions to such issues in the 127.0.0.0/8 domain... but I believe that it should be pretty simple to write the code that will resolve this and other issues.
I do not have the time and resources to do so but it's doable.

**Comment by pushrax** [comment]
Supporting both in Chihaya seems reasonable and fairly straightforward given the existing individual support.

**Comment by mrd0ll4r** [comment]
I'd be fine with supporting both on different ports, but not on the same port. That just adds unneccessary overhead.

**Comment by pushrax** [comment]
Yeah, it has to be different ports. I don’t think most libraries can do both on the same port, would require some very low level hacks.

**Comment by f4nff** [comment]
Listening on different ports, http usually defaults to port 80, and https usually defaults to port 443.

**Comment by mrd0ll4r** [comment]
> http usually defaults to port 80, and https usually defaults to port 443.

FWIW, I strongly advise against running your public tracker on :80 or :443, for the very reason that these are the standard HTTP and HTTPS ports.

Tracker URLs are very persistent once they're published somewhere. Be it in tracker lists, people's retracker config or whatnot. Even after you shut down the tracker running on your domain, you'll still receive tons and tons of tracker requests.

This isn't a problem if you've been running the tracker on a non-standard port, because the operating system will take care of dropping these connections. But if you ran it on :443/:80 and now there's something else running there (say, a website), you'll have to deal with these requests for all eternity. And in addition to that, client implementations might be buggy and flood you with tracker requests as long as they don't receive a satisfactory answer.

**Comment by pushrax** [comment]
If you have a domain that's clearly a tracker though, e.g. `tracker.example.com`, then it generally wouldn't be an issue since you wouldn't reuse the domain.

> we've tried supporting both in the past using cmux

Neat package! Definitely falls into the hack category for me :P
