### ISSUE TITLE
Race condition when accessing UDP server socket

### ISSUE THREAD

**Issue by cenkalti** [chihaya/chihaya#437]
`Frontend.socket` field in `udp` package is accessed from 2 goroutines. Found it with race detector while testing my program.

```
WARNING: DATA RACE
Read at 0x00c00019c100 by goroutine 32:
  .../vendor/github.com/chihaya/chihaya/frontend/udp.(*Frontend).Stop.func1()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:107 +0x93

Previous write at 0x00c00019c100 by goroutine 20:
  .../vendor/github.com/chihaya/chihaya/frontend/udp.(*Frontend).listenAndServe()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:123 +0xff
  .../vendor/github.com/chihaya/chihaya/frontend/udp.NewFrontend.func2()
      /Users/cenk/go/src/.../vendor/github.com/chihaya/chihaya/frontend/udp/frontend.go:88 +0x3c
```

Set in here: https://github.com/chihaya/chihaya/blob/8f0fc7ba1086d2480f101332101e57b7137c197e/frontend/udp/frontend.go#L123

And read in here: https://github.com/chihaya/chihaya/blob/8f0fc7ba1086d2480f101332101e57b7137c197e/frontend/udp/frontend.go#L107

**Comment by mrd0ll4r** [comment]
Hmm, that's strange. The good news is that the faulty read occurs when we shut down the frontend, but still, maybe not optimal. Maybe there's a proper way of closing just the receiving end of that socket.

The idea is to set the read deadline to now, so that no more reading will be done (it'll deadline out), but all requests still being processed will finish to do so and send their replies.

**Comment by cenkalti** [comment]
@mrd0ll4r yes, it's not a big deal in usage but race detector complains when it's used in tests. I'm sure it can be fixed by protecting `t.socket` with a mutex. Do you want me to prepare a PR for this?

**Comment by mrd0ll4r** [comment]
I'm afraid that might add some noticable overhead - I'd rather figure out another way.

The thing is: We use the same "socket" for receiving and sending packets. I put socket in quotes because we're on UDP here, so we don't have the TCP-like byte stream, which is bidirectional and of which each direction can be closed independently. We use the same "socket" so that outgoing packets have the proper source port, but maybe we can achieve that in a different way? Alternatively, maybe there is a more proper way of stopping all outstanding reads on the socket, instead of setting the read deadline. We could just exit out of the loop on the next iteration, for example, but if there's not much traffic, this might take a while.

If you could figure out a solution to this, that'd be fantastic :) Otherwise no worries, we'll figure it out eventually, it's just a bit messy with Christmas rn. Also, Merry Christmas! :)
