### ISSUE TITLE
Improve logging w/ standard levels

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#44]
The current selection of log levels confused me. When `-v=0`, our "purging peers" is displayed, but not requests?

I think we need to come up with guidelines for our log lines and start sprinkling them _everywhere_.

**Comment by mrd0ll4r** [comment]
I think we should introduce an interface for a logger, something like

    type Logger interface {
        New(name string) Logger

    	Errorln(message string) //or maybe Fatalln, Fatal
    	Error(format string, a ...interface{})
    
    	Warnln(message string)
    	Warn(format string, a ...interface{})
    
    	Infoln(message string)
    	Info(format string, a ...interface{})
    
    	Debugln(message string)
    	Debug(format string, a ...interface{})
    
    	Traceln(message string)
    	Trace(format string, a ...interface{})
    }

Maybe we could even leave out the `*ln` functions...

Especially, I would want to include checks like `if glog.V(2)` in the respective functions (in this case `Infoln` and `Info`).

That allows us to just write something like `log.Debug("Reaped %d inactive torrents",reaped)` instead of the three-line `if` construct...

The `New` function allows us to name loggers by package, I guess that could be nice. Maybe we should do something like the syncthing guys, specifying an environmental variable defining which packages should log on debug level, or specify that by flags.

What do you think?

Just a sidenote: Why do we use `glog`?

**Comment by jzelinskie** [comment]
What your suggesting looks a lot like [capnslog](github.com/coreos/capnslog). Creating a logger for each package gets pretty annoying, especially when glog already points out the line in the file anyway. I'm not against leveled logging; in fact, that's why we originally chose glog. The `if` construct is very powerful and allows us to do things like [this](https://github.com/chihaya/chihaya/blob/b303f0e9f2883505322d38e7dc874ed6607cabc8/http/http.go#L54-L65). The only problem is that glog doesn't have debug/trace functions.

**Comment by mrd0ll4r** [comment]
Alright, I wrote [github.com/mrd0ll4r/logger](https://github.com/mrd0ll4r/logger), fork of [github.com/calmh/logger](https://github.com/calmh/logger).

I incorporated lots of the ideas and useful things from glog and calhm/logger and came up with this:

    // Logger is an interface for leveled loggers.
    // All logging methods must be thread-safe, no guarantee is provided regarding the other methods.
    type Logger interface {
    	// SetLevel instructs the logger to log everything above and including the provided level
    	SetLevel(LogLevel)
    	// Logs returns whether this logger logs the specified level
    	Logs(LogLevel) bool
    
    	// Debugln logs a debug-marked line
    	Debugln(val ...interface{})
    	// Debugf logs a debug-marked formatted line
    	Debugf(format string, val ...interface{})
    
    	// Verboseln logs a verbose-marked line
    	Verboseln(val ...interface{})
    	// Verbosef logs a verbose-marked formatted line
    	Verbosef(format string, val ...interface{})
    
    	// Infoln logs an info-marked line
    	Infoln(val ...interface{})
    	// Infof logs an info-marked formatted line
    	Infof(format string, val ...interface{})
    
    	// Okln logs an OK-marked line
    	Okln(val ...interface{})
    	// Okf logs an OK-marked formatted line
    	Okf(format string, val ...interface{})
    
    	// Warnln logs a warn-marked line
    	Warnln(val ...interface{})
    	// Warnf logs a warn-marked formatted line
    	Warnf(format string, val ...interface{})
    
    	// Fatalln logs a fatal-marked line and exits the program with return code 1
    	Fatalln(val ...interface{})
    	// Fatalf logs a fatal-marked formatted line and exits the program with return code 1
    	Fatalf(format string, val ...interface{})
    }

This allows us to set levels, log on different levels and check if we log a specific level (`Logs(LogLevel)`). I also included useful log leves that cannot be logged directly (`Everything` and `Off`).

There is a `DefaultLogger` which, by default, is a `StdlibLogger` - it offers some methods in addition to the interface, namely `SetOutput(io.Writer)` `SetFlags(int)` and `SetPrefix(string)`. If you provide the `log.Lshortfile` or `log.Llongfile` flags, it will log the file position. Keep in mind that this is slow (run the benchmarks). Also keep in mind that this is not any more slow than glog, because it works the same way.
Also, the `StdlibLogger` supports the environment(al?) variable `LOGGER_DISCARD`, which disables all logging. This is useful for benchmarks :)

I included some more useful implementations, namely a `MultiLogger` to log to multiple underlying `Logger`s and a `Selective` logger, where you can enable/disable some levels.

Test coverage is around 60-70%, because logging the `StdlibLogger` is annoying. It's basically just a wrapper around `log`, and I guess that works.

The `StdlibLogger` performs "do not log if level is too low" checks on every call - this makes things easier for us, and is very fast if the level is too low.

Maybe I should and will change the exact levels (e.g. there is no `Error`, but there is an `OK` level), tell me what you think about it

**Comment by jzelinskie** [comment]
I like this logger a lot, but there seems to be lots of traction for logrus in the Go community. Any thoughts on logrus?

**Comment by mrd0ll4r** [comment]
I tried it, iirc it was slow. Then again we don't log all of our requests, so it might be okay.

**Comment by jzelinskie** [comment]
We went with logrus.
